format = """\
${directory} â”‚ ${hostname}${custom.subnet}${container}${localip}\
${git_branch}${git_commit}${git_state}${git_status}${git_metrics}\
${golang}${lua}${nodejs}${python}${rust}${package}\
${fill}\
${battery}${jobs}${memory_usage}${shlvl}\
${time}${custom.tz} â”‚ ${username}${sudo}\
\
${line_break}\
\
${character}
"""

###########################################################################

[battery]
  charging_symbol = 'ó°‚„'
  discharging_symbol = 'ó°‚ƒ'
  empty_symbol = 'ó°‚'
  format = '([${symbol}${percentage}](${style}) â”‚ )'
  full_symbol = 'ó°¹'
  unknown_symbol = 'ó°½'

  [[battery.display]]
    style = 'bold red'
    threshold = 10

  [[battery.display]]
    style = 'bold yellow'
    threshold = 30

[cmd_duration]
  format = '([${duration}](${style}) â”‚ )'
  min_time = 10_000
  style = 'white'

[container]
  format = '( [${symbol}](${style}))'
  style = 'blue'
  symbol = 'â¬¢'

[custom]
  [custom.subnet]
    command = '[[ -n "$SUBNET" ]] && echo ".${SUBNET}" || echo ""'
    format = "[${output}](${style})"
    style = 'blue'
    when = true

  [custom.tz]
    command = 'date +%Z'
    format = '[${output}](${style})'
    style = 'dimmed white'
    when = 'true'

[directory]
  format = '[${path}](${style})[${read_only}](${read_only_style})'
  style = 'blue'
  truncate_to_repo = false
  truncation_length = 8
  truncation_symbol = './'

[fill]
  symbol = ' '

[git_branch]
  always_show_remote = true
  format = '( â”‚ ${symbol}[${branch}](${style}))'
  style = 'dimmed white'
  symbol = 'î‚ '
  truncation_length = 20

[git_commit]
  format = '( [${hash}${tag}](${style}))'
  style = 'dimmed white'
  tag_disabled = false

[git_metrics]
  added_style = 'white'
  deleted_style = 'white'
  disabled = false
  format = '((+${added})(${added_style})(-${deleted})(${deleted_style}))'
  ignore_submodules = true

[git_state]
  format = '( [${state}(${progress_current}/${progress_total})]($style))'
  style = 'bold white'

[git_status]
  format = '( [${all_status}${ahead_behind}]($style))'
  style = 'white'

[golang]
  format = '( [${symbol}](${style}))'
  style = 'white'
  symbol = 'ğŸ¹'
  version_format = '${raw}'

[hostname]
  format = '[${hostname}](${style})'
  ssh_only = false
  ssh_symbol = 'ğŸŒ'
  style = 'blue'

[jobs]
  disabled = false
  format = '([${symbol}${number}](${style}) â”‚ )'
  style = 'bold red'

[localip]
  disabled = false
  format = '( [${localipv4}]($style))'
  ssh_only = false
  style = 'blue'

[lua]
  format = '( [${symbol}](${style}))'
  style = 'white'
  symbol = 'ğŸŒ™'
  version_format = '${raw}'

[memory_usage]
  disabled = false
  format = '(${symbol}[${ram}(|${swap})](${style}) â€¹ )'
  style = 'bold red'
  symbol = 'ğŸ'
  threshold = 80

[nodejs]
  format = '( [${symbol}](${style}))'
  style = 'white'
  symbol = 'îœ˜ '
  version_format = '${raw}'

[package]
  format = '( [${symbol}${version}](${style}))'
  style = 'white'
  symbol = 'ğŸ“¦'
  version_format = '${raw}'

[python]
  format = '( [${symbol}](${style}))'
  style = 'white'
  symbol = 'ğŸ'
  version_format = '${raw}'

[rust]
  format = '( [${symbol}](${style}))'
  style = 'white'
  symbol = 'ğŸ¦€'
  version_format = '${raw}'

[shlvl]
  disabled = false
  format = '([${symbol}${shlvl}]($style) â€¹ )'
  style = 'bold red'
  symbol = 'â†•ï¸'
  threshold = 3

[sudo]
  disabled = false
  format = '( [${symbol}]($style))'
  symbol = 'ğŸ§™'

[time]
  disabled = false
  format = '[${time}](${style})'
  style = 'dimmed white'
  time_format = '%T'

[username]
  format = '[${user}](${style})'
  show_always = true
  style_root = 'dimmed white'
  style_user = 'dimmed white'
